# Comment out the class property to enable debug from that class
log4j.rootCategory=INFO, A1

log4j.appender.A1=org.apache.log4j.RollingFileAppender
log4j.appender.A1.MaxFileSize=5MB
log4j.appender.A1.MaxBackupIndex=12
log4j.appender.A1.File=${PROGRAM_FILE_PATH.PARENT_PATH}/${PROGRAM_FILE_PATH.STEM}.log
log4j.appender.A1.Append=true
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %.30c - %m%n

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%.30c - %m%n

log4j.logger.excel2csv=DEBUG
#log4j.logger.excel2csv.ProcessDocuments=DEBUG
#log4j.logger.excel2csv.GetIterator=DEBUG
#log4j.logger.Excel.Sheet.Iterator=DEBUG
#log4j.logger.FileIterator=DEBUG
log4j.logger.CellRowIterator=DEBUG
#log4j.logger.SheetIterator=DEBUG
#log4j.logger.OLE=DEBUG
#log4j.logger.OLE.Workbooks=DEBUG
#log4j.logger.OLE.Workbook=DEBUG
#log4j.logger.OLE.Names=DEBUG
#log4j.logger.OLE.Name=DEBUG
#log4j.logger.OLE.Worksheets=DEBUG
#log4j.logger.OLE.Worksheet=DEBUG
#log4j.logger.OLE.Rows=DEBUG
log4j.logger.OLE.Cells=DEBUG
#log4j.logger.OutputValue=DEBUG
#log4j.logger.YamlDocument=DEBUG
#log4j.logger.YamlDocumentTemplate=DEBUG
